apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namespace: orangy-dev

# Image tag — Jenkins CI will update this automatically
images:
  - name: backend-image
    newName: ghcr.io/vedantkhursange/orangy-backend
    newTag: dev-latest

patches:
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: backend
      spec:
        replicas: 1
